#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 13 17:59:47 2017

@author: xu
"""
import tensorflow as tf

input1 = tf.constant([1.0,2.0,3.0],name = "input1")
input2 = tf.Variable(tf.random_uniform([3]),name = "input2")
output = tf.add_n([input1,input2],name = "add")
writer = tf.summary.FileWriter("/home/xu/桌面/xu/DeepLearininginAction/log",tf.get_default_graph())
writer.close()

